-- 3НФ: справочники Role/Category/Manufacturer/Supplier/PickupPoint вынесены отдельно.
CREATE DATABASE IF NOT EXISTS shoes CHARACTER SET utf8mb4;
USE shoes;

CREATE TABLE IF NOT EXISTS Role (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  Name VARCHAR(40) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS User (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  RoleID INT NOT NULL,
  FIO VARCHAR(150) NOT NULL,
  Login VARCHAR(100) UNIQUE NOT NULL,
  Password VARCHAR(100) NOT NULL,
  FOREIGN KEY (RoleID) REFERENCES Role(ID)
);

CREATE TABLE IF NOT EXISTS Category (
  ID INT AUTO_INCREMENT PRIMARY KEY, Name VARCHAR(80) UNIQUE NOT NULL);
CREATE TABLE IF NOT EXISTS Manufacturer (
  ID INT AUTO_INCREMENT PRIMARY KEY, Name VARCHAR(80) UNIQUE NOT NULL);
CREATE TABLE IF NOT EXISTS Supplier (
  ID INT AUTO_INCREMENT PRIMARY KEY, Name VARCHAR(80) UNIQUE NOT NULL);
CREATE TABLE IF NOT EXISTS PickupPoint (
  ID INT AUTO_INCREMENT PRIMARY KEY, Address VARCHAR(255) UNIQUE NOT NULL);

CREATE TABLE IF NOT EXISTS Product (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  Article VARCHAR(20) UNIQUE NOT NULL,
  Name VARCHAR(150) NOT NULL,
  Unit VARCHAR(20) NOT NULL,
  Price DECIMAL(10,2) NOT NULL,
  SupplierID INT, ManufacturerID INT, CategoryID INT,
  Discount INT DEFAULT 0,
  Stock INT NOT NULL DEFAULT 0,
  Description TEXT,
  ImagePath VARCHAR(255),
  FOREIGN KEY (SupplierID)    REFERENCES Supplier(ID),
  FOREIGN KEY (ManufacturerID) REFERENCES Manufacturer(ID),
  FOREIGN KEY (CategoryID)    REFERENCES Category(ID)
);

CREATE TABLE IF NOT EXISTS `Order` (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  OrderDate DATE NOT NULL,
  DeliveryDate DATE,
  PickupPointID INT NOT NULL,
  ClientFIO VARCHAR(150),
  Code INT NOT NULL,
  Status VARCHAR(40) NOT NULL,
  FOREIGN KEY (PickupPointID) REFERENCES PickupPoint(ID)
);

CREATE TABLE IF NOT EXISTS OrderItem (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  OrderID INT NOT NULL, ProductID INT NOT NULL, Qty INT NOT NULL DEFAULT 1,
  FOREIGN KEY (OrderID) REFERENCES `Order`(ID),
  FOREIGN KEY (ProductID) REFERENCES Product(ID)
);

INSERT IGNORE INTO Role(Name) VALUES ('Администратор'),('Менеджер'),('Клиент');
